version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - embeddedstructfieldcheck
    - err113
    - exhaustruct
    - funcorder
    - godot
    - interfacebloat
    - ireturn
    - mnd
    - nlreturn
    - noinlineerr
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 120
      statements: 40
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
    perfsprint:
      errorf: false
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: function-length
          disabled: true
        - name: use-errors-new
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: struct-tag
          arguments:
            - "validate,-"
        - name: line-length-limit
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    gofumpt:
      module-path: "github.com/mymmrac/lithium"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
