services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5432:5432"
